FROM scratch
LABEL org.entando.bundle-name="entando-training-2024"
ADD .entando/output/descriptors/ .
ADD microfrontends/hero-widget/dist widgets/hero-widget
ADD microfrontends/hero-table-widget/dist widgets/hero-table-widget
