FROM scratch
LABEL org.entando.bundle-name="entando-training-2024"
ADD .entando/output/descriptors/ .
ADD microfrontends/hero-form-widget/dist widgets/hero-form-widget
ADD microfrontends/hero-table-widget/dist widgets/hero-table-widget
ADD microfrontends/simple-mfe-config/dist widgets/simple-mfe-config
ADD microfrontends/epc-example/build widgets/epc-example
